name: Docker-CI-Pipeline
on: push
jobs:
  docker-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Build docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v2 .
      
      - name: Verify created image
        run: docker images

      - name: create container
        run: docker run --name python-app -itd -p 8080:8080 ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v2

      - name: view container
        run: docker ps

      - name: check output
        run: curl http://localhost:8080
            
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v2 

      - name: Docker container cleanup
        run: docker rm python-app
          

   
